return {
    --     {
    --         "catppuccin/nvim",
    --         as = "catppuccin",
    --         lazy = false,
    --         priority = 1000,
    --         config = function()
    --             require("catppuccin").setup({
    --                 flavour = "macchiato", -- latte, frappe, macchiato, mocha
    --                 background = {         -- :h background
    --                     light = "latte",
    --                     dark = "mocha",
    --                 },
    --                 transparent_background = true,
    --                 term_colors = false,
    --                 dim_inactive = {
    --                     enabled = false,
    --                     shade = "dark",
    --                     percentage = 0.15,
    --                 },
    --                 no_italic = false, -- Force no italic
    --                 no_bold = false,   -- Force no bold
    --                 styles = {
    --                     comments = { "italic" },
    --                     conditionals = { "italic" },
    --                     loops = {},
    --                     functions = {},
    --                     keywords = {},
    --                     strings = {},
    --                     variables = {},
    --                     numbers = {},
    --                     booleans = {},
    --                     properties = {},
    --                     types = {},
    --                     operators = {},
    --                 },
    --                 color_overrides = {},
    --                 custom_highlights = function(colors)
    --                     return {
    --                         LineNr = { fg = colors.surface2 }
    --                     }
    --                 end,
    --                 integrations = {
    --                     cmp = true,
    --                     gitsigns = true,
    --                     nvimtree = true,
    --                     telescope = true,
    --                     notify = false,
    --                     mini = false,
    --                     harpoon = true,
    --                     mason = true,
    --                     -- For more plugins integrations please scroll down (https://github.com/catppuccin/nvim#integrations)
    --                 },
    --             })
    --
    --             -- setup must be called before loading
    --             vim.cmd.colorscheme "catppuccin"
    --         end
    --     },
}
